name:                aoc2018
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/morteako/aoc2018#readme
license:             BSD3
author:              Morten Kolstad
maintainer:          example@example.com
copyright:           2018 Morten Kolstad
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - time
  - extra
  - multiset
  - split
  - mtl

executables:
  aoc2018:
    source-dirs:      src
    main:             Main.hs
